# Generated by Django 3.2.15 on 2022-08-16 15:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pearljam_fansite', '0004_auto_20220815_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlbumReview',
            new_name='Post',
        ),
    ]
