# Generated by Django 3.2.15 on 2022-08-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pearljam_fansite', '0006_alter_comment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='album_release',
            field=models.TextField(blank=True),
        ),
    ]
