# Generated by Django 3.2.15 on 2022-09-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pearljam_fansite', '0011_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
