# Generated by Django 3.2.15 on 2022-09-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pearljam_fansite', '0013_comment_last_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['last_modified']},
        ),
    ]
