# Generated by Django 3.2.15 on 2022-09-13 10:48

from django.db import migrations, models
import pearljam_fansite.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pearljam_fansite', '0014_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(validators=[pearljam_fansite.validators.textfield_not_empty]),
        ),
    ]
